### ISSUE TITLE
Can't figure out how to pass a IVectorView to a function that expects a IIterable

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/windows-rs#1953]
I'm trying to update a crate to windows 0.39 (from 0.38), and am running into a problem. I have code that roughly looks like this:
```rust
let updates = update_manager.GetAppAndOptionalStorePackageUpdatesAsync()?.get()?;

let download_operation = update_manager.RequestDownloadAndInstallStorePackageUpdatesAsync(updates)?;
```
I removed some unnecessary code relative to the original, which can be found [here](https://github.com/JuliaLang/juliaup/blob/ebddf1fc8ef9cfdc1ee6f434d69fcf6f809501f0/src/command_selfupdate.rs#L90).

This code used to work with v0.38, but now errors with a message
```
    Checking juliaup v1.6.13-alpha.0 (C:\Users\david\source\juliaup)
error[E0277]: the trait bound `InParam<'_, IIterable<StorePackageUpdate>>: From<IVectorView<StorePackageUpdate>>` is not satisfied
    --> src\command_selfupdate.rs:95:49
     |
95   |         let download_operation = update_manager.RequestDownloadAndInstallStorePackageUpdatesAsync(updates)?;
     |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<IVectorView<StorePackageUpdate>>` is not implemented for `InParam<'_, IIterable<StorePackageUpdate>>`
     |
     = help: the following other types implement trait `From<T>`:
               <InParam<'a, T> as From<std::option::Option<&'a T>>>
               <InParam<'a, U> as From<&'a T>>
               <InParam<'a, bool> as From<bool>>
               <InParam<'a, f32> as From<f32>>
               <InParam<'a, f64> as From<f64>>
               <InParam<'a, i16> as From<i16>>
               <InParam<'a, i32> as From<i32>>
               <InParam<'a, i64> as From<i64>>
             and 7 others
     = note: required because of the requirements on the impl of `Into<InParam<'_, IIterable<StorePackageUpdate>>>` for `IVectorView<StorePackageUpdate>`
     = note: required because of the requirements on the impl of `TryFrom<IVectorView<StorePackageUpdate>>` for `InParam<'_, IIterable<StorePackageUpdate>>`
note: required by a bound in `StoreContext::RequestDownloadAndInstallStorePackageUpdatesAsync`
    --> C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.39.0\src\Windows\Services\Store\mod.rs:1870:137
     |
1870 | ...ackageUpdate>>, Error = E0>,
     |                    ^^^^^^^^^^ required by this bound in `StoreContext::RequestDownloadAndInstallStorePackageUpdatesAsync`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `juliaup` due to previous error
```
and I can't figure out what to do :) Any help would be greatly appreciated!

**Comment by davidanthoff** [comment]
Ok, I figured it out, I just have to pass this with a `&` in front of it.

One thing that would be really great is if the change log had some hints about things like this. I took another look at it, and I think there was really nothing that could have pointed me in this direction :)

**Comment by rylev** [comment]
Thanks for this report. It would be possible for us to make the previous code work. However, the intent behind requiring the `&` is to encourage folks to borrow the parameters (since that's all the function needs). This prevents always passing things by value and thus encouraging over cloning. 

This is the same reason why if a Rust function takes a `&T` you cannot pass a `T` even though the Rust language could have made this just work. 

However, we could have made a different choice, so it's something for us to consider. One advantage that Rust the language has that we don't is control over the compiler error messages.

**Comment by davidanthoff** [comment]
I do like the new choice, no complaints there at all. It would just be great to get some more informative change log :)
