### ISSUE TITLE
Example RSS reader sample does not build with rust 1.52.1

### ISSUE THREAD

**Issue by darkdescendant** [microsoft/windows-rs#792]
Following the example RSS reader from here: https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows

Fresh install of rust 1.52.1

Source attached to issue.

[rss_reader.zip](https://github.com/microsoft/windows-rs/files/6456368/rss_reader.zip)

```
PS C:\Users\darkd\source\repos\rust\rss_reader> cargo run

   Compiling rss_reader v0.1.0 (C:\Users\darkd\source\repos\rust\rss_reader)
error[E0107]: this enum takes 2 type arguments but only 1 type argument was supplied
   --> src\main.rs:7:14
    |
7   | fn main() -> Result<()> {
    |              ^^^^^^ -- supplied 1 type argument
    |              |
    |              expected 2 type arguments
    |
note: enum defined here, with 2 type parameters: `T`, `E`
   --> C:\Users\darkd\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\result.rs:241:10
    |
241 | pub enum Result<T, E> {
    |          ^^^^^^ -  -
help: add missing type argument
    |
7   | fn main() -> Result<(), E> {
    |                       ^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
error: could not compile `rss_reader`

To learn more, run the command again with --verbose.
PS C:\Users\darkd\source\repos\rust\rss_reader> rustc --version

rustc 1.52.1 (9bc8c42bb 2021-05-09)
PS C:\Users\darkd\source\repos\rust\rss_reader> 
```

**Comment by kennykerr** [comment]
FYI @stevewhims

**Comment by stevewhims** [comment]
Thanks, all! I've published a fix to the topic (sorry about the error!). :)

**Comment by kennykerr** [comment]
Thanks Steve!
