### ISSUE TITLE
Developing with `windows` crate on linux

### ISSUE THREAD

**Issue by Libadoxon** [microsoft/windows-rs#3361]
### Summary

Using the feature `Win32_Devices_DeviceAndDriverInstallation`, which feature seach tells me to use, doesn't work as rust can't find the Win32 module. This is a regression and doesn't happen with `0.57.0`.

### Crate manifest

```TOML
[package]
name = "ms-device-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
windows = { version = "0.57.0", features = [
  "Win32_Devices_DeviceAndDriverInstallation",
] }
```

### Crate code

```Rust
use windows::Win32::Devices::DeviceAndDriverInstallation::{
    SetupDiGetClassDevsA, DIGCF_DEVICEINTERFACE, DIGCF_PRESENT,
};

fn main() {
    let dev_info_set =
        unsafe { SetupDiGetClassDevsA(None, None, None, DIGCF_PRESENT | DIGCF_DEVICEINTERFACE) };
}
```

**Comment by Libadoxon** [comment]
Running my code (with version `0.58.0`, sry for copying the wrong version) fails with:

```
error[E0433]: failed to resolve: could not find `Win32` in `windows`
 --> src/main.rs:1:14
  |
1 | use windows::Win32::Devices::DeviceAndDriverInstallation::{
  |              ^^^^^ could not find `Win32` in `windows`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `ms-device-test` (bin "ms-device-test") due to 1 previous error
```

Using cargo version `cargo 1.83.0 (5ffbef321 2024-10-29)` installed using `rustup toolchain install stable`. When changing version to `0.57.0` (or lower) it finds the module. I'm on Linux, I'm not sure if this is important.

**Comment by riverar** [comment]
Ah right, support for Linux was dropped as part of https://github.com/microsoft/windows-rs/pull/3143 (additional discussion https://github.com/microsoft/windows-rs/issues/3155#issuecomment-2220832167).

Unless you're working with DirectWrite Core or maybe DirectX Shader Compiler, I don't believe anything else is in scope from a support perspective. (Sorry!)

**Comment by Libadoxon** [comment]
Well that's annoying, I really don't like the development experience on windows. I of course understand, that most of this crate only works on windows, but after `0.57.0` `rust-analyzer` is no longer able to see the semantics of the crate, which makes developing with it on Linux a lot harder. Is there some way to still see the semantics while on Linux?

**Comment by kennykerr** [comment]
You can cross-compile on Linux - e.g. compile with `--target x86_64-pc-windows-gnu` - this should work fine and tested as part of [cross.yml](https://github.com/microsoft/windows-rs/blob/master/.github/workflows/cross.yml).

What you can't do is target Linux, which doesn't make sense anyway since these are Windows operating system APIs.

**Comment by Libadoxon** [comment]
I know but how can I make `rust-analyzer` see the semantics of the crate, to get auto completion and diagnostics?

**Comment by kennykerr** [comment]
That sounds like a good question for the rust-analyzer folks. Maybe open an issue on their repo. 🙂

**Comment by riverar** [comment]
I think you want to set `rust-analyzer.cargo.target` (preference) to `x86_64-pc-windows-gnu` or the target you wish for it to use.

**Comment by Libadoxon** [comment]
I fixed it by setting 
```toml
[build]
target = "x86_64-pc-windows-gnu"
```
in `.cargo/config.toml`

Thx for the help
