### ISSUE TITLE
Bug: Project compile properly with `0.33.0` version but not with `0.34.0`

### ISSUE THREAD

**Issue by qarmin** [microsoft/windows-rs#1637]
### Which crate is this about?

windows

### Crate version

0.34.0

### Summary

App worked fine with windows-rs `0.33.0` but fails to compile with `0.34.0` version 

### Toolchain version/configuration

x86_64_windows_gnu
Wine 7.4

### Reproducible example

```rust
Below, because in this place I can't drop files
```

### Crate manifest

```toml
[package]
name = "win_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dependencies.windows]
version = "0.34.0"
features = [
    "alloc",
    "Data_Xml_Dom",
    #"Foundation_Numerics",# ld: cannot find -ld2d1
    # Used in Bad data, not touch
    "Win32_Foundation",
    "Win32_Graphics_Printing",
    "Win32_Graphics_Gdi",
    # Normal
    "Win32_AI",
    "Win32_AI_MachineLearning",
    "Win32_AI_MachineLearning_DirectML",
    "Win32_AI_MachineLearning_WinML",
    "Win32_Data",
    "Win32_Data_HtmlHelp",
    "Win32_Data_RightsManagement",
    "Win32_Data_Xml",
    "Win32_Data_Xml_MsXml",
    "Win32_Data_Xml_XmlLite",
    "Win32_Devices",
    "Win32_Devices_AllJoyn",
    "Win32_Devices_BiometricFramework",
    "Win32_Devices_Bluetooth",
    "Win32_Devices_Communication",
    "Win32_Devices_DeviceAccess",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_DeviceQuery",
    "Win32_Devices_Display",
    "Win32_Devices_Enumeration",
    "Win32_Devices_Enumeration_Pnp",
    "Win32_Devices_Fax",
    "Win32_Devices_FunctionDiscovery",
    "Win32_Devices_Geolocation",
    "Win32_Devices_HumanInterfaceDevice",
    "Win32_Devices_ImageAcquisition",
    "Win32_Devices_PortableDevices",
    "Win32_Devices_Properties",
    "Win32_Devices_Pwm",
    "Win32_Devices_Sensors",
    "Win32_Devices_SerialCommunication",
    "Win32_Devices_Tapi",
    "Win32_Devices_Usb",
    "Win32_Devices_WebServicesOnDevices",
    "Win32_Foundation",
    "Win32_Gaming",
    "Win32_Globalization",
    "Win32_Graphics",
    "Win32_Graphics_CompositionSwapchain",
    "Win32_Graphics_DXCore",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D10",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D11on12",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Direct3D9on12",
    "Win32_Graphics_Direct3D_Dxc",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_DirectDraw",
    "Win32_Graphics_DirectManipulation",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Hlsl",
    "Win32_Graphics_Imaging",
    "Win32_Graphics_Imaging_D2D",
    "Win32_Graphics_OpenGL",
    "Win32_Graphics_Printing",
    "Win32_Graphics_Printing_PrintTicket",
    "Win32_Management",
    "Win32_Management_MobileDeviceManagementRegistration",
    "Win32_Media",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Apo",
    "Win32_Media_Audio_DirectMusic",
    "Win32_Media_Audio_DirectSound",
    "Win32_Media_Audio_Endpoints",
    "Win32_Media_Audio_XAudio2",
    "Win32_Media_DeviceManager",
    "Win32_Media_DirectShow",
    "Win32_Media_DirectShow_Xml",
    "Win32_Media_DxMediaObjects",
    "Win32_Media_KernelStreaming",
    "Win32_Media_LibrarySharingServices",
    "Win32_Media_MediaFoundation",
    "Win32_Media_MediaPlayer",
    "Win32_Media_Multimedia",
    "Win32_Media_PictureAcquisition",
    "Win32_Media_Speech",
    "Win32_Media_Streaming",
    "Win32_Media_WindowsMediaFormat",
    "Win32_NetworkManagement",
    "Win32_NetworkManagement_Dhcp",
    "Win32_NetworkManagement_Dns",
    "Win32_NetworkManagement_InternetConnectionWizard",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_MobileBroadband",
    "Win32_NetworkManagement_Multicast",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_NetBios",
    "Win32_NetworkManagement_NetManagement",
    "Win32_NetworkManagement_NetShell",
    "Win32_NetworkManagement_NetworkDiagnosticsFramework",
    "Win32_NetworkManagement_NetworkPolicyServer",
    "Win32_NetworkManagement_P2P",
    "Win32_NetworkManagement_QoS",
    "Win32_NetworkManagement_Rras",
    "Win32_NetworkManagement_Snmp",
    "Win32_NetworkManagement_WNet",
    "Win32_NetworkManagement_WebDav",
    "Win32_NetworkManagement_WiFi",
    "Win32_NetworkManagement_WindowsConnectNow",
    "Win32_NetworkManagement_WindowsConnectionManager",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_NetworkManagement_WindowsNetworkVirtualization",
    "Win32_Networking",
    "Win32_Networking_ActiveDirectory",
    "Win32_Networking_BackgroundIntelligentTransferService",
    "Win32_Networking_Clustering",
    "Win32_Networking_HttpServer",
    "Win32_Networking_Ldap",
    "Win32_Networking_NetworkListManager",
    "Win32_Networking_RemoteDifferentialCompression",
    "Win32_Networking_WebSocket",
    "Win32_Networking_WinHttp",
    "Win32_Networking_WinInet",
    "Win32_Networking_WinSock",
    "Win32_Networking_WindowsWebServices",
    "Win32_Security",
    "Win32_Security_AppLocker",
    "Win32_Security_Authentication",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authentication_Identity_Provider",
    "Win32_Security_Authorization",
    "Win32_Security_Authorization_UI",
    "Win32_Security_ConfigurationSnapin",
    "Win32_Security_Credentials",
    "Win32_Security_Cryptography",
    "Win32_Security_Cryptography_Catalog",
    "Win32_Security_Cryptography_Certificates",
    "Win32_Security_Cryptography_Sip",
    "Win32_Security_Cryptography_UI",
    "Win32_Security_DiagnosticDataQuery",
    "Win32_Security_DirectoryServices",
    "Win32_Security_EnterpriseData",
    "Win32_Security_ExtensibleAuthenticationProtocol",
    "Win32_Security_Isolation",
    "Win32_Security_LicenseProtection",
    "Win32_Security_NetworkAccessProtection",
    "Win32_Security_Tpm",
    "Win32_Security_WinTrust",
    "Win32_Security_WinWlx",
    "Win32_Storage",
    "Win32_Storage_Cabinets",
    "Win32_Storage_CloudFilters",
    "Win32_Storage_Compression",
    "Win32_Storage_DataDeduplication",
    "Win32_Storage_DistributedFileSystem",
    "Win32_Storage_EnhancedStorage",
    "Win32_Storage_FileHistory",
    "Win32_Storage_FileServerResourceManager",
    "Win32_Storage_FileSystem",
    "Win32_Storage_Imapi",
    "Win32_Storage_IndexServer",
    "Win32_Storage_InstallableFileSystems",
    "Win32_Storage_IscsiDisc",
    "Win32_Storage_Jet",
    "Win32_Storage_OfflineFiles",
    "Win32_Storage_OperationRecorder",
    "Win32_Storage_Packaging",
    "Win32_Storage_Packaging_Appx",
    "Win32_Storage_Packaging_Opc",
    "Win32_Storage_ProjectedFileSystem",
    "Win32_Storage_StructuredStorage",
    "Win32_Storage_Vhd",
    "Win32_Storage_VirtualDiskService",
    "Win32_Storage_Vss",
    "Win32_Storage_Xps",
    "Win32_Storage_Xps_Printing",
    "Win32_System",
    "Win32_System_AddressBook",
    "Win32_System_Antimalware",
    "Win32_System_ApplicationInstallationAndServicing",
    "Win32_System_ApplicationVerifier",
    "Win32_System_AssessmentTool",
    "Win32_System_Com",
    "Win32_System_Com_CallObj",
    "Win32_System_Com_ChannelCredentials",
    "Win32_System_Com_Events",
    "Win32_System_Com_Marshal",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Com_UI",
    "Win32_System_Com_Urlmon",
    "Win32_System_ComponentServices",
    "Win32_System_Console",
    "Win32_System_Contacts",
    "Win32_System_CorrelationVector",
    "Win32_System_DataExchange",
    "Win32_System_DeploymentServices",
    "Win32_System_DesktopSharing",
    "Win32_System_DeveloperLicensing",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_Ceip",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_Debug_WebApp",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_Diagnostics_ProcessSnapshotting",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_DistributedTransactionCoordinator",
    "Win32_System_Environment",
    "Win32_System_ErrorReporting",
    "Win32_System_EventCollector",
    "Win32_System_EventLog",
    "Win32_System_EventNotificationService",
    "Win32_System_GroupPolicy",
    "Win32_System_HostCompute",
    "Win32_System_HostComputeNetwork",
    "Win32_System_HostComputeSystem",
    "Win32_System_Hypervisor",
    "Win32_System_IO",
    "Win32_System_Iis",
    "Win32_System_Ioctl",
    "Win32_System_JobObjects",
    "Win32_System_Js",
    "Win32_System_Kernel",
    "Win32_System_LibraryLoader",
    "Win32_System_Mailslots",
    "Win32_System_Mapi",
    "Win32_System_Memory",
    "Win32_System_Memory_NonVolatile",
    "Win32_System_MessageQueuing",
    "Win32_System_MixedReality",
    "Win32_System_Mmc",
    "Win32_System_Ole",
    "Win32_System_ParentalControls",
    "Win32_System_PasswordManagement",
    "Win32_System_Performance",
    "Win32_System_Performance_HardwareCounterProfiling",
    "Win32_System_Pipes",
    "Win32_System_Power",
    "Win32_System_ProcessStatus",
    "Win32_System_RealTimeCommunications",
    "Win32_System_Recovery",
    "Win32_System_Registry",
    "Win32_System_RemoteAssistance",
    "Win32_System_RemoteDesktop",
    "Win32_System_RemoteManagement",
    "Win32_System_RestartManager",
    "Win32_System_Restore",
    "Win32_System_Rpc",
    "Win32_System_Search",
    "Win32_System_Search_Common",
    "Win32_System_SecurityCenter",
    "Win32_System_ServerBackup",
    "Win32_System_Services",
    "Win32_System_SettingsManagementInfrastructure",
    "Win32_System_SetupAndMigration",
    "Win32_System_Shutdown",
    "Win32_System_SideShow",
    "Win32_System_SqlLite",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SubsystemForLinux",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_TaskScheduler",
    "Win32_System_Threading",
    "Win32_System_Time",
    "Win32_System_TpmBaseServices",
    "Win32_System_TransactionServer",
    "Win32_System_UpdateAgent",
    "Win32_System_UpdateAssessment",
    "Win32_System_UserAccessLogging",
    "Win32_System_VirtualDosMachines",
    "Win32_System_WinRT",
    "Win32_System_WinRT_AllJoyn",
    "Win32_System_WinRT_Composition",
    "Win32_System_WinRT_CoreInputView",
    "Win32_System_WinRT_Direct3D11",
    "Win32_System_WinRT_Display",
    "Win32_System_WinRT_Graphics",
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_System_WinRT_Graphics_Direct2D",
    "Win32_System_WinRT_Graphics_Imaging",
    "Win32_System_WinRT_Holographic",
    "Win32_System_WinRT_Isolation",
    "Win32_System_WinRT_ML",
    "Win32_System_WinRT_Media",
    "Win32_System_WinRT_Pdf",
    "Win32_System_WinRT_Printing",
    "Win32_System_WinRT_Shell",
    "Win32_System_WinRT_Storage",
    "Win32_System_WinRT_Xaml",
    "Win32_System_WindowsProgramming",
    "Win32_System_WindowsSync",
    "Win32_System_Wmi",
    "Win32_UI",
    "Win32_UI_Accessibility",
    "Win32_UI_Animation",
    "Win32_UI_ColorSystem",
    "Win32_UI_Controls",
    "Win32_UI_Controls_Dialogs",
    "Win32_UI_Controls_RichEdit",
    "Win32_UI_HiDpi",
    "Win32_UI_Input",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_Ink",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Pointer",
    "Win32_UI_Input_Radial",
    "Win32_UI_Input_Touch",
    "Win32_UI_Input_XboxController",
    "Win32_UI_InteractionContext",
    "Win32_UI_LegacyWindowsEnvironmentFeatures",
    "Win32_UI_Magnification",
    "Win32_UI_Notifications",
    "Win32_UI_Ribbon",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_TabletPC",
    "Win32_UI_TextServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Wpf",
    "Win32_UI_Xaml",
    "Win32_UI_Xaml_Diagnostics",
    "Win32_Web",
    "Win32_Web_MsHtml",
]

```

### Expected behavior

App should compile with 0.34.0

Project to test -[WinProject.zip](https://github.com/microsoft/windows-rs/files/8356274/WinProject.zip)
 

### Actual behavior

App not compile

### Additional comments

Compilation log
```
   Compiling windows v0.34.0
    Building [=====================>      ] 9/11: windows
012c:fixme:file:server_get_file_info Unsupported info class e
error[E0609]: no field `Invoke` on type `&IWSManSession_Vtbl`
    --> C:\users\rafal\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.34.0\src\Windows\Win32\System\RemoteManagement\mod.rs:2970:51
     |
2970 | ...   (::windows::core::Interface::vtable(self).Invoke)(::core::mem::transmute_copy(self), actionuri.into_param().abi(), resourceuri.into...

     |                                                 ^^^^^^
     |
help: one of the expressions' fields has a field of the same name
     |
2970 |         (::windows::core::Interface::vtable(self).base.Invoke)(::core::mem::transmute_copy(self), actionuri.into_param().abi(), resourceuri.in
to_param().abi(), parameters.into_param().abi(), ::core::mem::transmute(flags), ::core::mem::transmute(&mut result__)).from_abi::<super::super::Foundation::BSTR>(result__)
     |                                                   +++++
help: a field with a similar name exists
     |
2970 |         (::windows::core::Interface::vtable(self).Invoke2)(::core::mem::transmute_copy(self), actionuri.into_param().abi(), resourceuri.into_p
aram().abi(), parameters.into_param().abi(), ::core::mem::transmute(flags), ::core::mem::transmute(&mut result__)).from_abi::<super::super::Foundation::BSTR>(result__)
     |                                                   ~~~~~~~

    Building [=====================>      ] 9/11: windows
For more information about this error, try `rustc --explain E0609`.
    Building [=====================>      ] 9/11: windows
error: could not compile `windows` due to previous error
```

**Comment by riverar** [comment]
Looks like an IDispatch related bug.

Simpler repro:

## Manifest
```toml
[package]
name = "app"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.windows]
version = "0.34.0"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_RemoteManagement",
]

```

## Code
```rust
fn main() { }
```

**Comment by kennykerr** [comment]
Thanks for the minimal repro. 😉

**Comment by kennykerr** [comment]
[0.35.0](https://github.com/microsoft/windows-rs/releases/tag/0.35.0) is published and includes this fix.
