### ISSUE TITLE
Link error with SystemServices::*

### ISSUE THREAD

**Issue by goooosick** [microsoft/windows-rs#688]
When I add `Windows::Win32::SystemServices::*` to build.rs in the message_box example, it gives a link error

```
libmessage_box_bindings-50cf4ae052037129.rlib(message_box_bindings-50cf4ae052037129.3wf6ms64or2zgsrg.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlCaptureContext2 referenced in function _ZN20message_box_bindings7Windows5Win3214SystemServices18RtlCaptureContext217h1755c62a5ac68768E
libmessage_box_bindings-50cf4ae052037129.rlib(message_box_bindings-50cf4ae052037129.3wf6ms64or2zgsrg.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlGetReturnAddressHijackTarget referenced in function _ZN20message_box_bindings7Windows5Win3214SystemServices31RtlGetReturnAddressHijackTarget17h2408ee8023c586b7E
libmessage_box_bindings-50cf4ae052037129.rlib(message_box_bindings-50cf4ae052037129.3wf6ms64or2zgsrg.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlIsZeroMemory referenced in function _ZN20message_box_bindings7Windows5Win3214SystemServices15RtlIsZeroMemory17h28347cd208f23874E
libmessage_box_bindings-50cf4ae052037129.rlib(message_box_bindings-50cf4ae052037129.3wf6ms64or2zgsrg.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlNormalizeSecurityDescriptor referenced in function _ZN20message_box_bindings7Windows5Win3214SystemServices30RtlNormalizeSecurityDescriptor17he362d2bcdf67b27cE
```

**Comment by kennykerr** [comment]
At least some of the functions you mentioned appear to be new to Windows 10 - it may be that you have an older SDK that lacks the libs necessary to support these functions. Unfortunately, the Rust compiler seems to try and resolve all externs even if they're not actually being called. 

I think we're getting close getting DLL imports working in Rust: https://github.com/rust-lang/rust/issues/58713

Until then, you can probably work around this by avoiding the wildcard or updating your dev box with the latest Windows SDK.

**Comment by goooosick** [comment]
Thanks for the quick response :). It works after updating Windows SDK to 10.0.19041.0.
