### ISSUE TITLE
implement windows::core::IUnknown

### ISSUE THREAD

**Issue by lzybkr** [microsoft/windows-rs#1475]
I'm trying to implement `IUnknown` like this:

```Rust
use windows as Windows;
#[implement(Windows::core::IUnknown)]
struct HelloData;
```

And I get this error:
```
error: `Windows.core.IUnknown` is not a class or interface
```

I'm not having trouble implementing other interfaces so it seems to be specific to `IUnknown`.

As a workaround, I think I can find a marker interface to implement but it's a little weird to have to do that.

**Comment by kennykerr** [comment]
The `implement` macro just received a major overhaul (https://github.com/microsoft/windows-rs/issues/1345). That update should be published next week but you can try it out by pointing directly at GitHub for now. Note that `IUnknown` is always implemented so you need not mention it directly. Here's a simple example:

```rust
use windows::core::*;

#[implement()]
struct Sample(i32);

impl Drop for Sample {
    fn drop(&mut self) {
        println!("dropping {}", self.0);
    }
}

fn main() -> Result<()> {
    let a: IUnknown = Sample(123).into();
    let _b: IUnknown = a.clone(); // AddRef
    let _c: IUnknown = a.cast()?; // QueryInterface

    Ok(())
}
```

**Comment by lzybkr** [comment]
Thanks, that works with `0.28`.

It's not entirely obvious though. It might be worth adding support for something more explicit even if it doesn't change code gen.

**Comment by kennykerr** [comment]
The error message with the latest version is a little more helpful, I think...

```
D:\temp>cargo run
   Compiling temp v0.1.0 (D:\temp)
error[E0119]: conflicting implementations of trait `std::convert::From<Sample>` for type `windows::core::IUnknown`
  --> src\main.rs:10:1
   |
10 | #[implement(IUnknown)]
   | ^^^^^^^^^^^^^^^^^^^^^^
   | |
   | first implementation here
   | conflicting implementation for `windows::core::IUnknown`
   |
   = note: this error originates in the attribute macro `implement` (in Nightly builds, run with -Z macro-backtrace for more info)
```
