### ISSUE TITLE
Linker failure after upgrading to 0.22 and using prepackaged APIs

### ISSUE THREAD

**Issue by LGUG2Z** [microsoft/windows-rs#1250]
Earlier I [updated a project to use the new prepackaged APIs](https://github.com/LGUG2Z/komorebi/commit/18f34babfa847996d517dbf89760de5e3ff4282c) and while this builds and installs ok for me locally on the latest stable version of Windows 10, it [ultimately fails on CI](https://github.com/LGUG2Z/komorebi/runs/4037226774?check_suite_focus=true#step:11:267) with the following error:

```
  = note: libsysinfo-e927e2d6b59d7d74.rlib(sysinfo-e927e2d6b59d7d74.sysinfo.207231cd-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol __imp_RtlGetVersion referenced in function _ZN4core3ops8function6FnOnce9call_once17habd1f14ae20f6bd2E
```

CI is running on `windows-latest` with `RUSTFLAGS: -Ctarget-feature=+crt-static` using the latest stable Rust toolchain targeting `x86_64-pc-windows-msvc`. [Full workflow file here for ref](https://github.com/LGUG2Z/komorebi/blob/master/.github/workflows/windows.yaml#L22).

I have been regularly keeping up with updates to `windows-rs` since ~0.11 but this is the first time I've encountered such an issue with the linker following an upgrade.

Is there anything obvious that I may be missing the configuration of this job that could cause the linker error I am seeing above?
