### ISSUE TITLE
Windows Only at root `windows` module for Linux

### ISSUE THREAD

**Issue by IpFruion** [microsoft/windows-rs#3155]
### Summary

System: MacOS Sonoma 14.1.1
RustC: `rustc 1.79.0 (129f3b996 2024-06-10)`

### Version Upgrade 0.57.0 -> 0.58.0
```
[dependencies.windows]
version = "0.58.0"
```
See Manifest and Code Implementation.

<img width="546" alt="image" src="https://github.com/microsoft/windows-rs/assets/2003353/4caae1c0-0de6-4a0b-af8d-39b50666d03c">

## Change Context

I believe the change was introduced in #3143 when the crate level attribute was added `#![cfg(windows)]` to the top of [windows/src/lib.rs](https://github.com/microsoft/windows-rs/blob/81ac76a07622e8e82f1b5274fd6db80ac735b5c6/crates/libs/windows/src/lib.rs#L9)

## Linux Testing

I believe the reason it wasn't captured in the CI pipeline during testing was because the linux tests import the `windows_core` crate directly instead of through the `windows::core` re-export [here](https://github.com/microsoft/windows-rs/blob/02c4f29d19fbe6d59b2ae0b42262e68d00438f0f/crates/tests/linux/Cargo.toml#L14)

### Crate manifest

```TOML
[package]
name = "windows-testing"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.58.0"
```

### Crate code

```Rust
use windows::core::s;

fn main() {
    let my_str = s!("testing");
    assert!(!my_str.0.is_null());
}
```

**Comment by kennykerr** [comment]
As you pointed out, the `windows` crate is not surprisingly Windows-only. 😊

https://github.com/microsoft/windows-rs/blob/db06b51c2ebb743efb544d40e3064efa49f28d38/crates/libs/windows/src/lib.rs#L9

So I'm not sure what the problem is. If I build your example to target Windows it compiles just fine. If I build it to target Linux then I get the expected error:

```
error[E0432]: unresolved import `windows::core`
 --> src/main.rs:1:14
  |
1 | use windows::core::s;
  |              ^^^^ could not find `core` in `windows`
```

**Comment by RunBolt** [comment]
Ah, previously in `0.57.0` version you could compile for Linux just fine (for at least just the bindings and some of the definitions / representations). Has that expectation changed for this crate?

**Comment by IpFruion** [comment]
Ah, I guess in `0.57.0` the windows core was able to be used (and compiles) in a target linux environment (for testing and development). The PR that merged the change looks like it was for the `strings` crate, which is why I am wondering why core was changed to be windows only via the `windows` crate?

**Comment by kennykerr** [comment]
Yes, non-Windows support is limited to the `windows-core` and `windows-result`. This is summarized in the readme for #3143.

**Comment by IpFruion** [comment]
Ok so it is intended that the `windows` crate (the one specified in the readme) to not re-export any other crates for Linux i.e. `windows::core` and other `windows::*` but rather users should install the separate crate `windows_core` as well if they want to compile it on Linux?

**Comment by kennykerr** [comment]
Clearly scoping and limiting support for non-Windows builds makes it clearer what is supported vs what happens to work by accident and reduces the overall support burden.

**Comment by IpFruion** [comment]
I agree with that sentiment wholeheartedly, what isn't clear to me is why the root `windows` crate has removed support for non-windows testing, development, etc. for all re-exported crates inside the root `windows` crate. Are you saying that he expectation is for something like

### Cargo.toml
```
[dependencies]
windows-sys = "0.52.0"
windows-core = "0.58.0"
...
```

### main.rs
```
use windows_sys::s;

fn main() {
    let my_str = s!("testing");
    assert!(!my_str.is_null());
}
```
To support non-windows to split out these dependencies from the `windows` crate? instead of using the re-export in the `windows` crate?

**Comment by riverar** [comment]
To your question: I think the expectation here is that you don't use any windows crates for non-Windows targets unless you're working with DirectWrite Core or maybe DirectX Shader Compiler. I don't believe anything else is in scope.

**Comment by IpFruion** [comment]
> To your question: I think the expectation here is that you don't use any windows crates for non-Windows targets unless you're working with DirectWrite Core or maybe DirectX Shader Compiler. I don't believe anything else is in scope.

Ah completely fair, then would it be fair to say that `windows_core` and `windows_result` are not necessarily in scope. I think it is ok to have crates that are windows only support, but then I wouldn't re-export them in the `windows` crate because the confusion is that `windows::core::*` has non-windows support (which it does from the `windows_core` crate) but it doesn't because the root `windows` crate forbids it.

If the intention is to have the `windows` crate to be ONLY for windows, then I would recommend that change be in a separate PR that is stated cleanly that the root `windows` crate is now only for the windows target.
